CREATE TABLE auth_sessions (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- token_hash = SHA-256(salt || token)，token 前缀 sess_（与 API Key sk-cf- 命名空间区分）；明文只存客户端
    token_hash     varchar(64) NOT NULL,
    user_id        bigint      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ip             varchar(45),
    user_agent     varchar(255),
    expires_at     timestamptz NOT NULL,
    last_active_at timestamptz NOT NULL DEFAULT now(),
    created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_auth_sessions_token_hash ON auth_sessions (token_hash);
CREATE INDEX idx_auth_sessions_user ON auth_sessions (user_id, expires_at);

-- 过期会话清理周期任务（01 §7.2 auth:session-cleanup）上线前由运维按需清理；
-- MVP 用 TTL 语义：登录新会话前懒删该用户过期会话。
