-- 0001_init（up）：CloudFog 22 张核心表建表。
-- 纪律（02 §11/§15）：本文件是表结构唯一事实源；索引名与 internal/model 的 gorm tag
-- 精确同名（供 12 §5.1 模型↔表结构一致性测试）；部分唯一/部分索引/分区仅在此声明。
-- usage_logs 为按月分区表，手工维护（02 §15.5）；本迁移含 2026-08 ~ 2027-08 月分区。

-- =====================================================================
-- 用户与权限域
-- =====================================================================

CREATE TABLE users (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               varchar(255) NOT NULL,
    phone               varchar(32),
    username            varchar(64) NOT NULL,
    password_hash       varchar(255),
    password_algo       varchar(20) NOT NULL DEFAULT 'argon2id',
    role                varchar(20) NOT NULL DEFAULT 'user',
    status              varchar(20) NOT NULL DEFAULT 'pending',
    default_group_id    bigint,
    timezone            varchar(64) NOT NULL DEFAULT 'UTC',
    version             bigint NOT NULL DEFAULT 0,
    risk_level          varchar(20) NOT NULL DEFAULT 'normal',
    concurrency_limit   int NOT NULL DEFAULT 0,
    last_login_at       timestamptz,
    source              varchar(20) NOT NULL DEFAULT 'user',
    source_id           varchar(128),
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    deleted_at          timestamptz
);
CREATE INDEX idx_users_role   ON users (role);
CREATE INDEX idx_users_status ON users (status);
CREATE UNIQUE INDEX uq_users_email_active    ON users (email)    WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_users_username_active ON users (username) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_users_phone_active    ON users (phone)    WHERE deleted_at IS NULL AND phone IS NOT NULL;
CREATE INDEX idx_users_risk_active ON users (risk_level) WHERE risk_level <> 'normal';

CREATE TABLE user_balances (
    user_id          bigint PRIMARY KEY,
    balance          numeric(20,10) NOT NULL DEFAULT 0,
    frozen           numeric(20,10) NOT NULL DEFAULT 0,
    total_recharged  numeric(20,10) NOT NULL DEFAULT 0,
    total_consumed   numeric(20,10) NOT NULL DEFAULT 0,
    quota_reset_at   timestamptz,
    version          bigint NOT NULL DEFAULT 0,
    updated_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_user_balances_balance_nonneg CHECK (balance >= 0),
    CONSTRAINT ck_user_balances_frozen_nonneg  CHECK (frozen  >= 0)
);

CREATE TABLE api_keys (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          bigint NOT NULL,
    group_id         bigint NOT NULL,
    name             varchar(100) NOT NULL,
    key_prefix       varchar(16) NOT NULL,
    key_hash         varchar(64) NOT NULL,
    status           varchar(20) NOT NULL DEFAULT 'active',
    expires_at       timestamptz,
    ip_whitelist     jsonb,
    model_whitelist  jsonb,
    quota_daily_usd  numeric(20,10),
    rpm_limit        int,
    tpm_limit        int,
    last_used_at     timestamptz,
    source           varchar(20) NOT NULL DEFAULT 'user',
    source_id        varchar(128),
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    deleted_at       timestamptz
);
CREATE UNIQUE INDEX uk_api_keys_key_hash ON api_keys (key_hash);
CREATE INDEX idx_api_keys_user_status   ON api_keys (user_id, status);
CREATE INDEX idx_api_keys_status_expires ON api_keys (status, expires_at);

CREATE TABLE groups (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              varchar(100) NOT NULL,
    rate_multiplier   numeric(10,4) NOT NULL DEFAULT 1.0,
    allowed_models    jsonb,
    rpm_limit         int NOT NULL DEFAULT 0,
    concurrency_limit int NOT NULL DEFAULT 0,
    daily_quota_usd   numeric(20,10),
    status            varchar(20) NOT NULL DEFAULT 'active',
    fallback_models   jsonb,
    sort_order        int NOT NULL DEFAULT 0,
    source            varchar(20) NOT NULL DEFAULT 'user',
    source_id         varchar(128),
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    deleted_at        timestamptz
);
CREATE UNIQUE INDEX uq_groups_name_active ON groups (name) WHERE deleted_at IS NULL;

CREATE TABLE user_allowed_groups (
    user_id  bigint NOT NULL,
    group_id bigint NOT NULL,
    PRIMARY KEY (user_id, group_id)
);

-- =====================================================================
-- 供应商与渠道域
-- =====================================================================

CREATE TABLE providers (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               varchar(50) NOT NULL,
    name               varchar(100) NOT NULL,
    protocol           varchar(30) NOT NULL,
    base_url           varchar(512) NOT NULL,
    auth_type          varchar(20) NOT NULL DEFAULT 'bearer',
    capabilities       jsonb NOT NULL DEFAULT '[]',
    docs_url           varchar(512) NOT NULL DEFAULT '',
    bill_on_failure    boolean NOT NULL DEFAULT false,
    bill_partial_stream boolean NOT NULL DEFAULT true,
    usage_reliable     boolean NOT NULL DEFAULT true,
    status             varchar(20) NOT NULL DEFAULT 'active',
    source             varchar(20) NOT NULL DEFAULT 'user',
    source_id          varchar(128),
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now(),
    deleted_at         timestamptz
);
CREATE UNIQUE INDEX uk_providers_code ON providers (code);

CREATE TABLE channels (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     varchar(100) NOT NULL,
    provider_id              bigint NOT NULL,
    provider_code            varchar(50) NOT NULL,
    base_url                 varchar(512),
    auth_type                varchar(20),
    credentials              jsonb NOT NULL DEFAULT '{}',
    cred_key_id              varchar(64),
    extra                    jsonb,
    proxy_id                 bigint,
    priority                 int NOT NULL DEFAULT 50,
    weight                   int NOT NULL DEFAULT 100,
    concurrency              int NOT NULL DEFAULT 3,
    rate_multiplier          numeric(10,4) NOT NULL DEFAULT 1.0,
    token_ratio              numeric(10,4) NOT NULL DEFAULT 1.0,
    zero_usage_count         int NOT NULL DEFAULT 0,
    status                   varchar(20) NOT NULL DEFAULT 'active',
    schedulable              boolean NOT NULL DEFAULT true,
    error_message            text,
    health_score             int NOT NULL DEFAULT 100,
    circuit_state            varchar(20) NOT NULL DEFAULT 'closed',
    circuit_open_until       timestamptz,
    circuit_fail_count       int NOT NULL DEFAULT 0,
    rate_limited_at          timestamptz,
    rate_limit_reset_at      timestamptz,
    overload_until           timestamptz,
    temp_unschedulable_until timestamptz,
    temp_unschedulable_reason text,
    last_used_at             timestamptz,
    expires_at               timestamptz,
    auto_pause_on_expired    boolean NOT NULL DEFAULT true,
    source                   varchar(20) NOT NULL DEFAULT 'user',
    source_id                varchar(128),
    created_at               timestamptz NOT NULL DEFAULT now(),
    updated_at               timestamptz NOT NULL DEFAULT now(),
    deleted_at               timestamptz
);
CREATE INDEX idx_channels_provider            ON channels (provider_id);
CREATE INDEX idx_channels_sched               ON channels (provider_code, priority, status);
CREATE INDEX idx_channels_status_sched        ON channels (status, schedulable);
CREATE INDEX idx_channels_circuit             ON channels (circuit_state, circuit_open_until);
CREATE INDEX idx_channels_rate_limit_reset_at ON channels (rate_limit_reset_at);
CREATE INDEX idx_channels_last_used_at        ON channels (last_used_at);
CREATE INDEX idx_channels_health_score        ON channels (health_score);
CREATE INDEX idx_channels_expires             ON channels (expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX idx_channels_deleted             ON channels (deleted_at) WHERE deleted_at IS NOT NULL;

CREATE TABLE channel_groups (
    channel_id bigint NOT NULL,
    group_id   bigint NOT NULL,
    PRIMARY KEY (channel_id, group_id)
);

CREATE TABLE proxies (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(100) NOT NULL,
    type       varchar(10) NOT NULL,
    host       varchar(255) NOT NULL,
    port       int NOT NULL,
    username   varchar(128) NOT NULL DEFAULT '',
    password   text NOT NULL DEFAULT '',
    status     varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);

-- =====================================================================
-- 模型域
-- =====================================================================

CREATE TABLE models (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             varchar(100) NOT NULL,
    provider_code    varchar(50) NOT NULL,
    display_name     varchar(100) NOT NULL DEFAULT '',
    context_window   int NOT NULL DEFAULT 0,
    max_output_tokens int NOT NULL DEFAULT 0,
    capabilities     jsonb NOT NULL DEFAULT '[]',
    billing_mode     varchar(20) NOT NULL DEFAULT 'token',
    fallbacks        jsonb,
    avg_first_token_ms int NOT NULL DEFAULT 0,
    status           varchar(20) NOT NULL DEFAULT 'active',
    sort_order       int NOT NULL DEFAULT 0,
    source           varchar(20) NOT NULL DEFAULT 'user',
    source_id        varchar(128),
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    deleted_at       timestamptz
);
CREATE INDEX idx_models_provider ON models (provider_code);
CREATE UNIQUE INDEX uq_models_name_active ON models (name) WHERE deleted_at IS NULL;

CREATE TABLE model_prices (
    id                              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id                        bigint NOT NULL,
    currency                        varchar(8) NOT NULL DEFAULT 'USD',
    input_price_per_1k              numeric(20,10) NOT NULL DEFAULT 0,
    output_price_per_1k             numeric(20,10) NOT NULL DEFAULT 0,
    cache_read_price_per_1k         numeric(20,10),
    cache_write_price_per_1k        numeric(20,10),
    long_context_threshold          int,
    long_context_input_price_per_1k numeric(20,10),
    long_context_output_price_per_1k numeric(20,10),
    per_request_price               numeric(20,10) NOT NULL DEFAULT 0,
    effective_from                  timestamptz NOT NULL,
    effective_to                    timestamptz,
    created_at                      timestamptz NOT NULL DEFAULT now(),
    updated_at                      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_model_prices_model_eff ON model_prices (model_id, effective_from);

CREATE TABLE model_mappings (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id     bigint,
    alias          varchar(100) NOT NULL,
    upstream_model varchar(100) NOT NULL,
    priority       int NOT NULL DEFAULT 0,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_model_mappings_channel_alias ON model_mappings (channel_id, alias);
CREATE INDEX idx_model_mappings_alias         ON model_mappings (alias);

-- =====================================================================
-- 计量域（usage_logs：按月分区只追加大表，手工维护 02 §15.5）
-- =====================================================================

CREATE TABLE usage_logs (
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    request_id        varchar(64) NOT NULL,
    user_id           bigint NOT NULL,
    api_key_id        bigint NOT NULL,
    channel_id        bigint NOT NULL,
    group_id          bigint,
    subscription_id   bigint,
    model             varchar(100) NOT NULL,
    upstream_model    varchar(100),
    provider_code     varchar(50) NOT NULL,
    mapping_chain     varchar(500),
    input_tokens      int NOT NULL DEFAULT 0,
    output_tokens     int NOT NULL DEFAULT 0,
    cache_read_tokens int NOT NULL DEFAULT 0,
    cache_write_tokens int NOT NULL DEFAULT 0,
    cache_write_ttl   varchar(8),
    image_count       int NOT NULL DEFAULT 0,
    request_count     int NOT NULL DEFAULT 0,
    input_cost        numeric(20,10) NOT NULL DEFAULT 0,
    output_cost       numeric(20,10) NOT NULL DEFAULT 0,
    cache_read_cost   numeric(20,10) NOT NULL DEFAULT 0,
    cache_write_cost  numeric(20,10) NOT NULL DEFAULT 0,
    total_cost        numeric(20,10) NOT NULL DEFAULT 0,
    upstream_cost     numeric(20,10) NOT NULL DEFAULT 0,
    rate_multiplier   numeric(10,4) NOT NULL DEFAULT 1.0,
    channel_multiplier numeric(10,4) NOT NULL DEFAULT 1.0,
    price_snapshot    jsonb,
    billing_mode      varchar(20) NOT NULL DEFAULT 'token',
    usage_source      varchar(20) NOT NULL DEFAULT 'upstream',
    stream            boolean NOT NULL DEFAULT false,
    duration_ms       int,
    first_token_ms    int,
    status_code       int NOT NULL DEFAULT 200,
    error_code        varchar(64),
    switch_count      int NOT NULL DEFAULT 0,
    degraded          boolean NOT NULL DEFAULT false,
    retry_count       int NOT NULL DEFAULT 0,
    client_ip         varchar(45),
    user_agent        varchar(512),
    created_at        timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id, created_at)  -- 分区表主键必须含分区键（02 §15.5）
) PARTITION BY RANGE (created_at);

CREATE TABLE usage_logs_202608 PARTITION OF usage_logs FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE usage_logs_202609 PARTITION OF usage_logs FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE usage_logs_202610 PARTITION OF usage_logs FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE usage_logs_202611 PARTITION OF usage_logs FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE TABLE usage_logs_202612 PARTITION OF usage_logs FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');
CREATE TABLE usage_logs_202701 PARTITION OF usage_logs FOR VALUES FROM ('2027-01-01') TO ('2027-02-01');
CREATE TABLE usage_logs_202702 PARTITION OF usage_logs FOR VALUES FROM ('2027-02-01') TO ('2027-03-01');
CREATE TABLE usage_logs_202703 PARTITION OF usage_logs FOR VALUES FROM ('2027-03-01') TO ('2027-04-01');
CREATE TABLE usage_logs_202704 PARTITION OF usage_logs FOR VALUES FROM ('2027-04-01') TO ('2027-05-01');
CREATE TABLE usage_logs_202705 PARTITION OF usage_logs FOR VALUES FROM ('2027-05-01') TO ('2027-06-01');
CREATE TABLE usage_logs_202706 PARTITION OF usage_logs FOR VALUES FROM ('2027-06-01') TO ('2027-07-01');
CREATE TABLE usage_logs_202707 PARTITION OF usage_logs FOR VALUES FROM ('2027-07-01') TO ('2027-08-01');
CREATE TABLE usage_logs_202708 PARTITION OF usage_logs FOR VALUES FROM ('2027-08-01') TO ('2027-09-01');
-- 后续月分区由 ops 周期任务/发布脚本预建（02 §9 归档与分区维护）；新分区须同样附带：
--   idx_usage_logs_status_code（部分索引，父表不允许建，只能逐分区建，02 §6.1）

-- 错误监控部分索引（分区父表禁止部分索引，须逐分区建；PG 索引名 schema 级唯一，逐分区命名）
CREATE INDEX idx_usage_logs_202608_status_code ON usage_logs_202608 (status_code) WHERE status_code >= 400;
CREATE INDEX idx_usage_logs_202609_status_code ON usage_logs_202609 (status_code) WHERE status_code >= 400;
CREATE INDEX idx_usage_logs_202610_status_code ON usage_logs_202610 (status_code) WHERE status_code >= 400;
CREATE INDEX idx_usage_logs_202611_status_code ON usage_logs_202611 (status_code) WHERE status_code >= 400;
CREATE INDEX idx_usage_logs_202612_status_code ON usage_logs_202612 (status_code) WHERE status_code >= 400;
CREATE INDEX idx_usage_logs_202701_status_code ON usage_logs_202701 (status_code) WHERE status_code >= 400;
CREATE INDEX idx_usage_logs_202702_status_code ON usage_logs_202702 (status_code) WHERE status_code >= 400;
CREATE INDEX idx_usage_logs_202703_status_code ON usage_logs_202703 (status_code) WHERE status_code >= 400;
CREATE INDEX idx_usage_logs_202704_status_code ON usage_logs_202704 (status_code) WHERE status_code >= 400;
CREATE INDEX idx_usage_logs_202705_status_code ON usage_logs_202705 (status_code) WHERE status_code >= 400;
CREATE INDEX idx_usage_logs_202706_status_code ON usage_logs_202706 (status_code) WHERE status_code >= 400;
CREATE INDEX idx_usage_logs_202707_status_code ON usage_logs_202707 (status_code) WHERE status_code >= 400;
CREATE INDEX idx_usage_logs_202708_status_code ON usage_logs_202708 (status_code) WHERE status_code >= 400;

CREATE INDEX idx_usage_logs_request_id      ON usage_logs (request_id);
CREATE INDEX idx_usage_logs_user_created    ON usage_logs (user_id, created_at DESC);
CREATE INDEX idx_usage_logs_key_created     ON usage_logs (api_key_id, created_at DESC);
CREATE INDEX idx_usage_logs_channel_created ON usage_logs (channel_id, created_at DESC);
CREATE INDEX idx_usage_logs_group_created   ON usage_logs (group_id, created_at DESC);
CREATE INDEX idx_usage_logs_request_created ON usage_logs (request_id, created_at);
CREATE INDEX idx_usage_logs_model           ON usage_logs (model, created_at DESC);

-- 只追加保障：禁止对 usage_logs 执行 UPDATE/DELETE（02 §6.1；DROP 分区归档不受影响）
CREATE OR REPLACE FUNCTION usage_logs_guard() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'usage_logs is append-only: UPDATE/DELETE forbidden (02 §6.1)';
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_usage_logs_no_write
    BEFORE UPDATE OR DELETE ON usage_logs
    FOR EACH ROW EXECUTE FUNCTION usage_logs_guard();

CREATE TABLE usage_daily_stats (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_date         date NOT NULL,
    user_id           bigint NOT NULL,
    api_key_id        bigint,
    model             varchar(100),
    channel_id        bigint,
    request_count     bigint NOT NULL DEFAULT 0,
    success_count     bigint NOT NULL DEFAULT 0,
    error_count       bigint NOT NULL DEFAULT 0,
    input_tokens      bigint NOT NULL DEFAULT 0,
    output_tokens     bigint NOT NULL DEFAULT 0,
    cache_read_tokens bigint NOT NULL DEFAULT 0,
    cache_write_tokens bigint NOT NULL DEFAULT 0,
    total_cost        numeric(20,10) NOT NULL DEFAULT 0,
    upstream_cost     numeric(20,10) NOT NULL DEFAULT 0,
    avg_duration_ms   int NOT NULL DEFAULT 0,
    avg_first_token_ms int NOT NULL DEFAULT 0,
    p95_duration_ms   int NOT NULL DEFAULT 0,
    duration_histogram jsonb,
    updated_at        timestamptz NOT NULL DEFAULT now()
);
-- 唯一（空值视为等价，PG15+ NULLS NOT DISTINCT）：用户维度行各维空值与明细维度不冲突
CREATE UNIQUE INDEX uk_usage_daily_dim ON usage_daily_stats
    (stat_date, user_id, model, api_key_id) NULLS NOT DISTINCT;
CREATE INDEX idx_usage_daily_stat_date ON usage_daily_stats (stat_date);

-- =====================================================================
-- 账单与支付域
-- =====================================================================

CREATE TABLE billing_ledger (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint NOT NULL,
    type            varchar(30) NOT NULL,
    amount          numeric(20,10) NOT NULL,
    overdraft       numeric(20,10) NOT NULL DEFAULT 0,
    balance_after   numeric(20,10) NOT NULL,
    request_id      varchar(64) NOT NULL DEFAULT '',
    usage_log_id    bigint,
    subscription_id bigint,
    payment_order_id bigint,
    description     varchar(500) NOT NULL DEFAULT '',
    operator_id     bigint,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_billing_ledger_balance_after_nonneg CHECK (balance_after >= 0)
);
CREATE INDEX idx_ledger_user_created  ON billing_ledger (user_id, created_at DESC);
CREATE INDEX idx_ledger_type_created  ON billing_ledger (type, created_at);
-- 防重最终防线（06 §10 / 02 §7.1）：同一请求只允许一条 settle / refund
CREATE UNIQUE INDEX uq_ledger_settle  ON billing_ledger (request_id) WHERE type = 'settle';
CREATE UNIQUE INDEX uq_ledger_refund  ON billing_ledger (request_id) WHERE type = 'refund';

CREATE TABLE subscription_plans (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(100) NOT NULL,
    price_usd       numeric(20,10) NOT NULL DEFAULT 0,
    duration_days   int NOT NULL,
    quota_usd       numeric(20,10),
    rate_multiplier numeric(10,4) NOT NULL DEFAULT 1.0,
    allowed_models  jsonb,
    status          varchar(20) NOT NULL DEFAULT 'active',
    source          varchar(20) NOT NULL DEFAULT 'user',
    source_id       varchar(128),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);
CREATE UNIQUE INDEX uk_subscription_plans_name ON subscription_plans (name);

CREATE TABLE subscriptions (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint NOT NULL,
    plan_id      bigint NOT NULL,
    status       varchar(20) NOT NULL DEFAULT 'pending',
    started_at   timestamptz NOT NULL,
    expires_at   timestamptz NOT NULL,
    period_index int NOT NULL DEFAULT 1,
    auto_renew   boolean NOT NULL DEFAULT false,
    quota_used   numeric(20,10) NOT NULL DEFAULT 0,
    quota_total  numeric(20,10),
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_subscription_period ON subscriptions (id, period_index);
CREATE INDEX idx_subscriptions_user_status   ON subscriptions (user_id, status);
CREATE INDEX idx_subscriptions_status_expires ON subscriptions (status, expires_at);

CREATE TABLE payment_providers (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       varchar(30) NOT NULL,
    name       varchar(100) NOT NULL,
    config     jsonb,
    enabled    boolean NOT NULL DEFAULT false,
    sort_order int NOT NULL DEFAULT 0,
    source     varchar(20) NOT NULL DEFAULT 'user',
    source_id  varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
);
CREATE UNIQUE INDEX uk_payment_providers_code ON payment_providers (code);

CREATE TABLE payment_orders (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no        varchar(64) NOT NULL,
    user_id         bigint NOT NULL,
    provider_code   varchar(30) NOT NULL,
    provider_trade_no varchar(128) NOT NULL DEFAULT '',
    amount          numeric(20,10) NOT NULL,
    currency        varchar(8) NOT NULL DEFAULT 'USD',
    exchange_rate   numeric(20,10) NOT NULL DEFAULT 1.0,
    credited_amount numeric(20,10) NOT NULL DEFAULT 0,
    type            varchar(20) NOT NULL,
    plan_id         bigint,
    status          varchar(20) NOT NULL DEFAULT 'pending',
    paid_at         timestamptz,
    expired_at      timestamptz,
    refund_no       varchar(64) NOT NULL DEFAULT '',
    refunded_amount numeric(20,10) NOT NULL DEFAULT 0,
    refunded_at     timestamptz,
    raw_notify      jsonb,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_payment_orders_no ON payment_orders (order_no);
CREATE UNIQUE INDEX uq_payment_orders_trade_no ON payment_orders (provider_trade_no) WHERE provider_trade_no <> '';
CREATE UNIQUE INDEX uq_payment_orders_refund_no ON payment_orders (refund_no) WHERE refund_no <> '';
CREATE INDEX idx_payment_orders_user_created   ON payment_orders (user_id, created_at DESC);
CREATE INDEX idx_payment_orders_status_expires ON payment_orders (status, expired_at);

-- =====================================================================
-- 幂等与审计
-- =====================================================================

CREATE TABLE idempotency_records (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope           varchar(50) NOT NULL,
    idempotency_key varchar(128) NOT NULL,
    result          jsonb,
    expires_at      timestamptz NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_idem_scope_key ON idempotency_records (scope, idempotency_key);
CREATE INDEX idx_idem_expires_at ON idempotency_records (expires_at);

CREATE TABLE audit_logs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    bigint,
    actor_type  varchar(20) NOT NULL,
    action      varchar(64) NOT NULL,
    target_type varchar(30) NOT NULL DEFAULT '',
    target_id   varchar(64) NOT NULL DEFAULT '',
    before      jsonb,
    after       jsonb,
    result      varchar(20) NOT NULL DEFAULT 'success',
    client_ip   varchar(45) NOT NULL DEFAULT '',
    user_agent  varchar(512) NOT NULL DEFAULT '',
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_actor_created  ON audit_logs (actor_id, created_at DESC);
CREATE INDEX idx_audit_action_created ON audit_logs (action, created_at);
CREATE INDEX idx_audit_target         ON audit_logs (target_type, target_id);

CREATE TABLE settings (
    key         varchar(64) PRIMARY KEY,
    value       jsonb,
    description varchar(255) NOT NULL DEFAULT '',
    updated_at  timestamptz NOT NULL DEFAULT now(),
    updated_by  bigint
);

-- =====================================================================
-- 外键（软删除业务实体一律 ON DELETE RESTRICT；usage_logs 为分区大表不加 FK）
-- =====================================================================

ALTER TABLE user_allowed_groups ADD CONSTRAINT fk_uag_user  FOREIGN KEY (user_id)  REFERENCES users (id)  ON DELETE RESTRICT;
ALTER TABLE user_allowed_groups ADD CONSTRAINT fk_uag_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE RESTRICT;
ALTER TABLE api_keys           ADD CONSTRAINT fk_apikey_user  FOREIGN KEY (user_id)  REFERENCES users (id)  ON DELETE RESTRICT;
ALTER TABLE api_keys           ADD CONSTRAINT fk_apikey_group FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE RESTRICT;
ALTER TABLE channels           ADD CONSTRAINT fk_channel_provider FOREIGN KEY (provider_id) REFERENCES providers (id) ON DELETE RESTRICT;
ALTER TABLE channels           ADD CONSTRAINT fk_channel_proxy    FOREIGN KEY (proxy_id)     REFERENCES proxies (id)    ON DELETE RESTRICT;
ALTER TABLE channel_groups     ADD CONSTRAINT fk_cg_channel FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE;
ALTER TABLE channel_groups     ADD CONSTRAINT fk_cg_group   FOREIGN KEY (group_id)   REFERENCES groups (id)   ON DELETE CASCADE;
ALTER TABLE model_prices       ADD CONSTRAINT fk_price_model FOREIGN KEY (model_id) REFERENCES models (id) ON DELETE CASCADE;
ALTER TABLE model_mappings     ADD CONSTRAINT fk_mapping_channel FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE;
ALTER TABLE subscriptions      ADD CONSTRAINT fk_sub_user FOREIGN KEY (user_id) REFERENCES users (id)  ON DELETE RESTRICT;
ALTER TABLE subscriptions      ADD CONSTRAINT fk_sub_plan FOREIGN KEY (plan_id) REFERENCES subscription_plans (id) ON DELETE RESTRICT;
ALTER TABLE payment_orders     ADD CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT;
ALTER TABLE payment_orders     ADD CONSTRAINT fk_order_plan FOREIGN KEY (plan_id) REFERENCES subscription_plans (id) ON DELETE RESTRICT;
ALTER TABLE billing_ledger     ADD CONSTRAINT fk_ledger_user  FOREIGN KEY (user_id)          REFERENCES users (id)          ON DELETE RESTRICT;
ALTER TABLE billing_ledger     ADD CONSTRAINT fk_ledger_order  FOREIGN KEY (payment_order_id) REFERENCES payment_orders (id) ON DELETE RESTRICT;
ALTER TABLE billing_ledger     ADD CONSTRAINT fk_ledger_sub    FOREIGN KEY (subscription_id)  REFERENCES subscriptions (id)  ON DELETE RESTRICT;
