// 由 design-tokens.json 生成 app/assets/css/tokens.css（唯一事实源 → --cf-* CSS 变量）。
// 用法：node scripts/build-tokens.mjs（postinstall / dev / build 前置）。
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const src = JSON.parse(readFileSync(join(root, 'design-tokens.json'), 'utf8'))

// 调色板引用 "group.name" → hex
const palette = (v) => {
  const [group, name] = String(v).split('.')
  const val = src.palette?.[group]?.[name]
  if (!val) throw new Error(`design-tokens: 未知调色板引用 ${v}`)
  return val
}
// 值 → 最终 CSS 值：hex / 调色板引用 / var(...) 等原样
const cssValue = (v) => (String(v).startsWith('#') || String(v).startsWith('var(')) ? v : palette(v)

// 16 进制混色（wh = 0..1 混入白色 / 0..-1 混入黑色）——EP --el-color-primary-light-N 语义
const mixHex = (hex, target, w) => {
  const h = hex.replace('#', '')
  const r = parseInt(h.slice(0, 2), 16); const g = parseInt(h.slice(2, 4), 16); const b = parseInt(h.slice(4, 6), 16)
  const t = parseInt(target.slice(1, 3), 16), u = parseInt(target.slice(3, 5), 16), v = parseInt(target.slice(5, 7), 16)
  const c = (x, y) => Math.round(x * (1 - Math.abs(w)) + y * Math.abs(w))
  const rr = w >= 0 ? c(r, t) : c(r, 0)
  const gg = w >= 0 ? c(g, u) : c(g, 0)
  const bb = w >= 0 ? c(b, v) : c(b, 0)
  return '#' + [rr, gg, bb].map((x) => x.toString(16).padStart(2, '0')).join('')
}
const lighten = (hex, n) => mixHex(hex, '#FFFFFF', n)
const darken = (hex, n) => mixHex(hex, '#000000', n)

const out = [`/* AUTO-GENERATED by scripts/build-tokens.mjs — 禁止手改。事实源: design-tokens.json */`, `:root {`]
for (const [k, v] of Object.entries(src.palette)) {
  for (const [name, value] of Object.entries(v)) out.push(`  --cf-${k}-${name}: ${value};`)
}
for (const [name, value] of Object.entries(src.spacing)) out.push(`  --cf-space-${name}: ${value};`)
for (const [name, value] of Object.entries(src.radius)) out.push(`  --cf-radius-${name}: ${value};`)
for (const [name, value] of Object.entries(src.shadow)) out.push(`  --cf-shadow-${name}: ${value};`)

const emitTheme = (theme) => {
  const t = src.themes[theme]
  for (const [k, v] of Object.entries(t.roles)) out.push(`  --cf-${k}: ${cssValue(v)};`)
  for (const [k, v] of Object.entries(t.elementBridge)) out.push(`  ${k}: ${cssValue(v)};`)
  // EP 主色阶族：--el-color-primary-light-3/5/7/8/9 + dark-2（按该主题主色混白/黑）
  const primary = palette(t.elementBridge['--el-color-primary'])
  out.push(`  --el-color-primary-light-3: ${lighten(primary, 0.3)};`)
  out.push(`  --el-color-primary-light-5: ${lighten(primary, 0.5)};`)
  out.push(`  --el-color-primary-light-7: ${lighten(primary, 0.7)};`)
  out.push(`  --el-color-primary-light-8: ${lighten(primary, 0.8)};`)
  out.push(`  --el-color-primary-light-9: ${lighten(primary, 0.9)};`)
  out.push(`  --el-color-primary-dark-2: ${darken(primary, 0.2)};`)
}
emitTheme('light')
out.push(`}`)
out.push(`html.dark {`)
emitTheme('dark')
out.push(`}`)
out.push(`:root { --cf-font-sans: ${src.fonts.sans}; --cf-font-mono: ${src.fonts.mono}; }`)

const cssPath = join(root, 'app/assets/css/tokens.css')
mkdirSync(dirname(cssPath), { recursive: true })
writeFileSync(cssPath, out.join('\n') + '\n')
console.log(`tokens.css regenerated (${out.length} lines)`)
