// 由 design-tokens.json 生成 app/assets/css/tokens.css（唯一事实源 → --cf-* CSS 变量）。
// 用法：node scripts/build-tokens.mjs（postinstall / dev / build 前置）。
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const src = JSON.parse(readFileSync(join(root, 'design-tokens.json'), 'utf8'))

const ref = (v) => {
  const [group, name] = String(v).split('.')
  const val = src.palette?.[group]?.[name]
  if (!val) throw new Error(`design-tokens: 未知引用 ${v}`)
  return val
}

const out = [`/* AUTO-GENERATED by scripts/build-tokens.mjs — 禁止手改。事实源: design-tokens.json */`, `:root {`]
for (const [k, v] of Object.entries(src.palette)) {
  for (const [name, value] of Object.entries(v)) out.push(`  --cf-${k}-${name}: ${value};`)
}
const themeOf = (theme) => {
  const t = src.themes[theme]
  for (const [k, v] of Object.entries(t.roles)) out.push(`  --cf-${k}: ${v.startsWith('#') ? v : ref(v)};`)
  for (const [k, v] of Object.entries(t.elementBridge)) out.push(`  ${k}: ${v.startsWith('#') ? v : ref(v)};`)
}
themeOf('light')
out.push(`}`)
out.push(`html.dark {`)
themeOf('dark')
out.push(`}`)
out.push(`:root { --cf-font-sans: ${src.fonts.sans}; --cf-font-mono: ${src.fonts.mono}; }`)

const cssPath = join(root, 'app/assets/css/tokens.css')
mkdirSync(dirname(cssPath), { recursive: true })
writeFileSync(cssPath, out.join('\n') + '\n')
console.log(`tokens.css regenerated (${out.length} lines)`)
